main: md.takkapi.mapImages.CustomMaps
authors: [Takkapi, BC5]
version: 1.1
name: MapImages
description: "Allows the loading of images onto maps"
api-version: 1.18

commands:
  getmap:
    description: "Load an image from a URL onto a map"
    usage: "/getmap <url>"
    permission: "mapimages.getmap"

permissions:
  mapimages.getmap:
    default: true
  mapimages.getmap.thinair:
    default: false